projects:
  - name: app1-prod
    rbac:
      - group: app1-owners
        clusterrole: admin
        users:
          - admin
      - group: app1-users
        clusterrole: cluster-admin
        users:
          - admin2
