channel: stable-4.12
version: 4.12.24
subscriptions:
  - name: rhacs-operator
    namespace: rhacs-operator
    channel: stable
    source: redhat-operators
  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: latest
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  - name: web-terminal
    namespace: openshift-operators
    channel: fast
    source: redhat-operators
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.8
    source: redhat-operators
    installPlanApproval: Manual
    targetNamespaces:
      - open-cluster-management

auth:
  enabled: true
acs:
  enabled: true
  pipelines: true
acm:
  enabled: true
  gitops_integration: false
sealedsecrets:
  enabled: true
gitops:
  enabled: true
allure:
  enabled: true
