channel: stable-4.12
version: 4.12.23
subscriptions:
  - name: rhacs-operator
    namespace: rhacs-operator
    channel: stable
    source: redhat-operators
  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: latest
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  - name: web-terminal
    namespace: openshift-operators
    channel: fast
    source: redhat-operators

auth:
  enabled: true
acs:
  enabled: true
  pipelines: false
sealedsecrets:
  enabled: true
gitops:
  enabled: true
allure:
  enabled: true
