{{- if not .Values.noacm }}

apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: {{ .Values.provider }}
    region: {{ .Values.region }}
    name: {{ .Values.clusterName }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: {{ .Values.managedSet }}
    managed: "true"
  name: {{ .Values.clusterName }}
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
spec:
  clusterName: {{ .Values.clusterName }}
  clusterNamespace: {{ .Values.clusterName }}
  clusterLabels:
    cloud: {{ .Values.provider }}
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
{{- end }}
