apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ssh-private-ssh-key
  namespace: {{ .Values.clusterName }}
spec:
  encryptedData:
    ssh-privatekey: AgBnh/wuOVuD4dIPJcNONMZigIUvH7FIrYA0OhWGYhdv0SGFpcOCrftrfGAcR9GSQJiAOTkM0IsHAmzsPwUKN5oNdZ4e+LpXKgsNH/aCGeDKkoS7vat/xcWwM5I30JS0ocshB7EQWe8aO54AfbW6dysFRhJsAIgAZWqMyoACC+ksE89jdHzSP77mi4z77SoYc1bw+uoAUoV5y82h4p2EeyFTPDiJF1mtt7f+QJRmSc7RNGR7xkulN45ryNo5KqWoXy0MrJ9s0on2zbpqK51+Y7FRIgubDIGgvvTYKAEpDY4BgxzINHrOA3L3vJ9fMowfDJQhQJMmNVMf36Ma1QMQyX3yFd88V/MqC6r9kAQpKKudF5ZN4ymGVerJEZf8pReR74paZcDbQMat1jcmicGUpFnaHB6L6M5f6Ftn0SvtteSm8YdOKmypQW1VpOsqEwiFYRsNUsMRW/Oov7sYRE2yEVXRp+g2iplq+19RVZN/OiUDhSwDLrY8SKnuWdFJuaxZbInThrFY90B8JZO3q1bi3qNsHCDHNUMEL8P1FV4uLQrTmfMn9eFJkYEUGFOuUwhYm+y50wOnE7fVC07zcMswQXV7R04BHN/wJA13HgHxYMbJQ+s8IBqE0FQFz5+pVyMrWWJhjp+m5qwc3Y4AiSysI68LihujpY9rq+prZk74FqEqahOGIC3DkvYjbAUV9vntB/thp0nXaVNM4SgLEPlq01cZsteSaQ/+L2wxQWHiYM6dg01gwvJep3jmbhNRqrM/s3Ndv7BJDWoP/EZvO/Iul2iAdFKn9dQyO2k6CCREVxyKb7//6B8NwVmWAXMda3A6lkLAYuQjCvuBg7U1xXQNJcUC6GNY5FzyZs7eJKX+QaMW671B+2kNKzdvCcRLim3GdQbFhCX+5NX5Z1OKeOlDXP6ghnDLHbx2Vks40WpM0rDwcczNc9vo7UwUsNND8qkDK+xvKIQaX4HQcOOOE/fTkDQ3KoEBbz1fk/YZoWYaPi0MzozQnk36qUDXezp4WfpFkNxTWVeWSjRn7YOa9L7LOtu051UHoPfi3NRtOU0m0/Cmr31P51BQ7DtHUQCmUJLUXBMrt5X9dpbHo0b/kLLQSHY17RDiwifhDhj/HxMHuMO1V5M314nPQgZrduv3P5DeJPdRdteB+FxozlUa931UcUsC9mS1eGdA9Lqi9UFmpw3555NJpEUIuxKYGiqfafz3Ta/ZP0gNPAHdsCmOUfUwyuHh3wfc3KJXw9Vz4mkhClFF2x4J0ivic5k9/IBF5u/e7JI9s8teimwvFWfZzSM+c0L7D+dQxFxDvK9f92Tq2mgI1KqvPYPTfglzRoU477gZzbSY8Rckp6mmbf5vIy6VuxfotbQ0BHAfcVcjuFXakIzRWeFL4W7O6cPcVufOYspZ5KA77BUVid7uIfRj1PVWDGrBVbXUG7CbA1U+aK7+hZsL4hW/Zfy/zMuQUrZCc56s7KjQSLZHvZHnn3/21/bEGRdOiKxposHvVg6Cb/C4h2Kvb5uvINcV+fpEhBqV0ONhlfZcMAniLre54rWrk2t1FUxXH3TXXhU6rfvjhVJvTX+9Mo4X/EuEofnckSXp8rTW0zU5+AJCb1RE8KGMy/vhHZmHhBwum9UX54n3xfgFwjEDmyI15iHjW/r7RsbqWNPtGrj8Iwh8fG/Bg58pfcdg2OtxX7icTyxlAOfe/Opw0yunjVreMW45c+wGn/FUO2tNtg7jdpSCHbD+jaOwQptb48OmecWzySFVfrYiCvq8UK6hgPqdr6B+UaXMW3O6Js8IbenLbB6K/bjh9AAcdRaoXn1dEIEmfKLgBAtxbwGTi2uWr6pxkxWqra/BA3INuBPjVMnNS3/ADaXIO8+qjyuyvPndy0B5V365d4DkmwwsX4q+Fj7n9p+ns4Ap8s/m5z1u2T3SYlLP5OV+5NRSraDy1wND7sV2PnGY7E+3SznJffIaWfmQ6Gg9LGCgQgux5uIRHVtqa593mP1dZ9pIqYVk/TEq+VtATfF1fi8FETzJC+ADRA+1i5TvmxgppJyMtv4lQMEABs9q2y00Iss6xKx0CihmZhldNElX5S6STYcQfqBg59Y3OMYm+mqbAhp9en1m0IUgTp3YOprMnEHMqxqZsF9GDlWdq4mPkPA5mak3QnEm97eMZmzorwggsjLhLnvUQL1UYxO1N3HuvUlcBffb8AqLe9+LG09VtRpo985XBGbW6IdHdWSubwFhRz6KpVxpScQl4ihdshWK+UsMPSl58zDtKpfm6gk6Y9CyybHYMUstJpVmvkqHJfu0CpGq13wfwq8xUmEkjNg/mVPG5rNaA5whpg7cOfBB91Hc/Oahx48RSO3LWl14XY42TY+m0Y8CmQLUhYGC1qp6UuyFp43usP1wDgLQW828q5Cl6yOrwTcC92P/TOYR/odFsc+hYeSE3lvu8qzbswdXlCNE/VA34UJybnPv5L2jcZKGOGUUy1XVY/8+RO8Q1vePeua64lLdMbR/MgD3Seo+Xe57hTg7Y3r9y+huYGei2rExe6ttqwbdVDiz54pK7+28uscSJSZEWaLbsUWXP/kBRwSsssKHYNYWOhrVvdwzzVzTI47Ye7fC3YOzfuxxAJwbtSXyT2YdsJ1ls3obYK4QztKOtF8WwnK8Awz3EVUYf8LTFzLENcBNomFEmtSvExNup5ZJGRpd0GGEiTak/vaPNTXLsNqHzEA07TOhDqCWDJjz/PpiOYPASf1sTDXtHCdzszBIwkBUafikYGCaVe/eB6l27N44oaJ9deUuenA1C53b8eB5+rqh36a2Lz3ZVTOPVfebbFFazKaqls5QPg/H2GEE/vkIy3bSBtH5Vcy6pDhWmR86td1TcgLTf9u6KTR1EOksIKMh+roG1dyZKMIdTyunNma01Oa8SWVs89CjeMxCfHBpAMXfSLjn4V5zXZZYXSKznzdng8W5F3/iSS3Vj/T0FoljwNEg2zSvEVKe+Dqcnpq4jGTmG0GLTYJx3xsTXy9a7VUYXs4i/AT5JCvvIfOyZ6k+6IpuCHcF+njW0zeAsoD/7B8Uc6x/TrDFsTYFOgdSLmfsZktwRywDR37GW3vOubA27/0Q3SrCQuwkzI3SqOOXnsT9QlLTHdnWwg6AsXWQ0wJa6E0mSg33AILmACISKf/Ba6GXRDTl8dr2NgXNQm5IfKJgOQsPmMBYPHdSWuqtCDEtacGplKnX1VCN7gOWOHNkrypKcBxMvWNdtsmwZ52SLBrGI3VTA/lyKyULwcM/PVyJhhYyUiWy+sqmogw+L+DZw10bFUBo016E+u3GBvlZ2k60fbyImtbw0mPcMXY/Ew5s4e1nuy5H4yd96R77ztKE2nGQs5CVNnFG1nlQk8kDCN+f3BEPUHRrRjAH2EDQisXRC8IUqoQr7ulBZymZoSDtRY2kT8DpVrpYBHh3XgjA3pxPzmDQ29EPjL7EtP1SmYGy+qWguZ8lqVgxR5w4WPjVoqllM61XtZeazONwhX5pcUwSeK4zwNdm38GpvZBjLrHO/w+HCRCGTynH7XWqZu3HvoMencxFlblpMHk/3zEVxbuTQAZc3MhCFFpDIka3NcreOZwR54f38ibLndDGj9FDcuWj3AD0wQzLnckJbL/8ubbwzJM1/4kZVyp0U37sFwj+BCxxo92pCXG7F6SzPoCqA37S6pnTD/IxoHsFAqUPgPfX/rjaYjg4hST3ZgEZDz+x4ZxnTjBWqdF5w4cj4DdCS01/fXNa37l2jj9f6lGTfqVxJ1999jihKvzr6XQNYauHudv6BVfms/KfgNU+6qEQBZ6Jdr5ehvNdNvGxrxnB7MBTw7sk2w6rcKONTTzKP+wJVzfO+gJmioqdhygpYdh3wgfQkB7zb0IIBBlS8UyDJjXI0qAZTPhYs6yRH0eW2vYPaSylJ93J/31zL5a3xnmghOxynrvAoOFQDx+aggCi+SUpwHEkGxgpy/MZ5IkuM/kUFmzYlFgLdxFvkuiR8RnwB/dJWfrhhFbmfp12eIdohD/45f6J8rjr2jJALbllkD5hF4QpKVKzOhkLlOKBNK9yVt0Wf/1OS476ql552bLHub0ZFTSP7NyHyQheVHkRZxTZ88S3ibL1ddhTZZFnKB76xfyr0NakhM2ltXswzk8XlUmPRf2YTPX0N1XUeGSf0r9Fnn8J7A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ssh-private-ssh-key
      namespace: {{ .Values.clusterName }}
    type: Opaque

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pull-secret
  namespace: {{ .Values.clusterName }}
spec:
  encryptedData:
    .dockerconfigjson: AgAVLQWv8T+NiGNvjqyvizT9Y4iAse3vryYiJN08R9795iPkaC95JVl5e9GupnMonK1z0vuCYPlm1rYyXOsQq/mFHBE4NTQHgYfpIijRsvcG31RLzhtA0B/W6aowpFY4fN92Wl0ds+wz4YIOIZt4rAYaxGSMLiBNzADEMGwSnYNREW3b2VOMz8inQGQBZ2bovvtxjOueKy0L2RSFYYThQJ1EIGBO1VzbIXa5Q1YV0AuMPvDkdtaNvPyM9fHcQAKT4cGCNa6rR6O9gE3ru35e5UydhiPY8v/ZXZkH6qATFD/mFA6PE+wDqPTERQw39z3nZgUPXDjcI5koNzC19cbEyD6xe5EydZFxskksebGl0z6xSckD8HoBCjBrsmife2PkvEhKgqs3kJyLL+3tCwOrHftc9S4s8KPtqPCWLPdjm2233Vgwo5iI2OeDnKpXoXOrB9pIUWR9rzzK4ty6GZP6Qp7h4EoPiy8RjdCJBcrgCIRfFcbx7+npzimEnI3iCitEK5fUTDB7+Pug/MWAOXjcB2/PzUgGBTN/+Yec5WjnM5pKqQ5TCr24GFZjtgvIJExfx+Ue2IwC7NssKOGamZ6yiXZVSABpcuoVArasBdBrGGjciHZ3JVf3OxkIpHbQgZ7+7eMOcckDeMnFMXcKksjm1aJTFvXvuJnIjTs6dvXIsYo8/AfoIMnWHYL9UIAjgLtelFPmYXvRb0xKvduDCVI0umWrTBReHaid5zXxzrqTK0JcD2ThtA1oYwT9Qj2k44xdxSHgUtaYikQ2md/+AQVNdKToL4A4Rjr0hfHaL6auQw3CDvbhXjspBD1tBLtRNFUsVox+QHLKqGFdXSDeYdKNYM0pNlh2bt3MpkPtp8lqxxT76U9X5/H/Nu14YD3+JAc5s4ADHLDpf5RJC0EXjJFIHOkrOak3hz3czp3ElTXZK/7T6kQ474PfoailriHz38TmTPTPuTb4KBgo2K0frq8EXG9UAc/84qpNVe60CpEJRpBuuv/RELbOtHKvhRlMwjwt8/yapenEVMhwDXAyvKEsDDb4TlK0MWWxIJQU4IxQNmOZiOoFqaqbyd/oG1QhD8VFqQq/SiQ32GuigQHHajEn0yy0qIG9wfkHJ/v4bdTUtAOLqTf0PJgUA4iUj9OgG0qbi74cr09l1viRhJ3M+Tv+bR+3d8mCg8He589ZbbZ2FUYwDYd0e/HvmY6dSuSRnT5QUwVUmhpzoppoxbVR9cEwVK7VCQvI8rZdWK3gMGh4U9y+0XwjyaEaVTSYlZqUKj912oJBta1q0a11oBrNU4XrD8pzLBNmYCi+YNfLlByUVsg3EMN7nL82VyFsvzkzQmNZmD4B7gsUQu37i3odJJVKrqc9cbbsn/tMQlAzVkR6dsOdSAj/TmRae+81iPicYVuvWaVsEXOa+/j0yq/f2tKWNDGhA4JtaYcwpLA25rEfqCMw8uTuUHm2nPmyJniWVAKpGVf1B1IW0WTmw0CvAbtcQCB/jHUj4ACsUsCmgzS8WrbV0ne9bMKgbOt6DpoH7TOHZGZy1rYGWUCJXS2Gah7JZJaH65yiMnQ8X3HPBOtWw3LhqMrn/h1QIoJM+QMyAQ0uuJk9dYdceRUujfIxZLrWdps+8u2Hc5OgP+k7XDbA2g7xLnh6KRLXZnUs7EYvPL0ZhvLPopNJiDq7UpA3I3uJ0sogvuSvnSOTeAtqA2EVLhsLOz/WooTxi1h/UHzoHTgGQ93bgwhrdtOySAHfSPOVr8VEi91+fHzIa6YVamm4csefqmd0e3nJG8UpYoLtmb1nHLa3QukDkaAeRrmvZzof+QHJ1jh4UKvu9plF76J58XUAlDDhvheQxpDJ279nRk12e1BA+faB51Xxv7X5qnafJkzVmnQWP8gY7CPMJ39JiC7xrdPEc0LA5ajycQP324wUaJG71gc7JZtieUYSdUzXN8KcwK2JS6OYDD4mdSFCNvDLpf3vAMnsy9B/G7x4+KQSZnLSC3/g0yppWSXrAVpfXW/sxdKa1KK0grjG4vdhB0d4bQpdoRkkJZEpGocUEeiaJv9fFxgcbRtXh4gScx8m2xpkwSVIRaFW6n3CAEwUJTHUHIoYTX/xY0aQBoHdREYsXK5bb8dMRqx7D4d+loPCj+plNZhJtRM/Zvtve26Or7WBFuoAES9+DBv4nkw5zL22/uYRkPOsOBr1tg0ogukEotlJNuNc8QXg9Ysrb84rxEyMSQsqzBU6aWbkYp8W8RAF7oUrM2fthutvW2lhWr/fRhkcCJIfMngta+1I8VXqZF+HNs2ZkeqDecIopXK+LtpEjHaRs+P2xFlk7r6wEf/15oVTJJjrm6dCESqLRWQoBmCnFQczRcgAhi3oErSPKWSwq7BX751gUIpQ8Tz4UqHoTxThywfOGipNhLxpUfxoHpQcgmY1SSvkk3LF9WHD5fsWCxoVe87TGRRcL/bhM+rWMQozKmhBWFiJcj8ZFzb0RHFWU1PRtAQ8o5rdNza+T0xaD0/5jaqO0PDxO0PTQSLPMIJp4HCyJmuHjfXGZ/ZpHomorbsMsVoTTnyfw4UMKIq9WfJIjPHKV71nFlu6p07O1MGjazAgxjM+l3fbzuh158ynegEDzzksI2Ww+N5l/eGcNfYUnL1caglOOgvVztPvow8UY6BMNU2ctO+jqHMEWXGMWrXg4L4ZBcG+YoZgpaN1rctHhUFoaKt4pI+jiDCI4OfsLNzsbjoUOiBxU79aqubd3OpzMrLL4vdnyqKN9+qYf8wj+GWM1tRTA884JVHlpVU0Uwda8RB0G5JVRFfYvDon1jRHDnWa0Q72L8GqiH7Rd2zqkvKhy3lVj6l4xVVpUQ5LsyeYWAhBIBBvWnv11qzphI3UJ92njg/O7/w0+jTyEda8h2F6BrLd5O5rIQFA47PRK8aqmR2VloqiW3BjPF8MZtv0d26+uUqCr2Npg2+n25fD7TB9ZBkgSH36DE2BdJF8aJK0o2ovWd9Sjym953ANxd+Ck4BcIJfx49RaxDhyu4ILQmu64i09tPMy9q91cornz83jyrCGf+HYGmmif7CEuw4mQvqLqTs+qgcCEYPvf4JnegF29PBu8RZpNYQslY/RiugdGKciQGqcg+Q3ygISPP3rva3N3nnLMrlEgYNDt1890WtJSbqr7X7QTjrWzWeGJ4Bh3tDWdlXLUYwmmlVM9CaRWZjDE8psY9TzVlWQfMhxIkR7OJnCvKpkH+0fKjsqUxelRveuKJo2xu0UzSJnxczWtqzsws5vyjBqgBnWzASIAQ6KuE4WlYT+isprOolvm15D2avRBiSlqM/AvKTktjTzMTwWHUMsmqbYCA8wAsYIG8XKo7uIen/SDIvrIAfa4oOZ62Exp7avaT9+AQ4Ypo9vxG/5EY+f2QzXSA1Anx63CeWci0Si12tmE1VwOlKvdnqX8XeFkArCnj/AbmjsASUdXZGwYMPlLcWy7KuUJ2jkGQqLDrDZOOgE4Av1uTgJt4C+PBgYGdYrBdk69QpiDnBW7RAXl19kcGkp1GymBl41JuRcgXXX5xuRwN4uy2oimLRM5iR+7pvBHK65BM4EjNanqG6mxNeMOL8Q4d4h8Fofw+XrCYpa6uuliJD+Qw1+LqmUI5pYO1BuC3q4TST3JHRNc+gDkAxXa59E/bGhb6yrtKUcWHyY0ihzEHa9gZDOoevNW2VUVAejhK7bQX5eofvYC5IeB6cHq2t4M2ACTk53vn1jgA/ig8HyAe53AQFpLT65mR8y70ZOZYNVLsFkd3MVfenWrcUiMhcx5TMQBT0M+A4NfZa1DKrCMuKXr5MIb3FORMq5iJLXJSZoIGfeibmjQ2hmdWEmtX4wIVIRzZpZhHt9gBotY7Y9EXxYQQ6tcGzc5dS5salA3l4jgV/2iq6FQUjyAP4t8nNiOs1EAJbwny/pELeILau4qi8QZdGLg/ZfcV/WI1Gtx88hAE1rzUOXmxj+9l4TDj/5s8bYq2DADPSYRmV7U4IthzWy2rwAyKk1TC4EJt3q7GCsflJR/gZxI+lAEPkJtZT/elRxT8yt304nrlRkNHKvtTaC1CpNIlhw3s/PlvaOO3kC7tkJHXn0jAGBIfEUxwIeMBIDY3kZulpSCRVi5eFdXhz0EhhsnONR1D6L3Ub07Zhzx8ep91TBkGUFwOTj8SIyFlH7NtjXxtwJ4+12yXFyGUMRsEx0hT9yNtCFn5mnQXfs5QDeMGQP5L6FFFNQBDkRnX+Quqjjpc3YtfYVRlbrMPbPbwcWgveVrXo53OzQ+II+ZV5JkVCupBIK4EZ7vAhpMRACQQyCBNrbZUukLyQZdWGwyiWpBxW06JSORSt9QrULYpexnyGNrpV+cz48IQdRDOTGlenTbVTpNMHygR5b1PuCUVqLO9kxBYzV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pull-secret
      namespace: {{ .Values.clusterName }}
    type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: install-config
  namespace: {{ .Values.clusterName }}
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: {{ .Values.clusterName }}
    baseDomain: {{ .Values.baseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        {{- if eq .Values.provider "Google" }}
        gcp:
          type: {{ .Values.workerType }}
        {{- end }}
        {{- if eq .Values.provider "Amazon" }}
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: {{ .Values.workerType }}
        {{- end }}
    compute:
      - hyperthreading: Enabled
        name: 'worker'
        replicas: {{ .Values.workerReplicas }}
        platform:
          {{- if eq .Values.provider "Google" }}
          gcp:
            type: {{ .Values.workerType }}
          {{- end }}
          {{- if eq .Values.provider "Amazon" }}
          aws:
            rootVolume:
              iops: 4000
              size: 100
              type: io1
            type: {{ .Values.workerType }}
          {{- end }}
    networking:
      networkType: OpenShiftSDN
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
      machineNetwork:
        - cidr: 10.0.0.0/16
      serviceNetwork:
        - 172.30.0.0/16
    platform:
      {{- if eq .Values.provider "Google" }}
      gcp:
        projectID: {{ .Values.project }}
        region: {{ .Values.region }}
      {{- end }}
      {{- if eq .Values.provider "Amazon" }}
      aws: 
        region: {{ .Values.region }}
      {{- end }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: {{ .Values.sshKey }}
