apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
  labels:
    cloud: {{ .Values.provider }}
    region: {{ .Values.region }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: {{ .Values.managedSet }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  baseDomain: {{ .Values.baseDomain }}
  clusterName: {{ .Values.clusterName }}
  installed: true
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    gcp:
      credentialsSecretRef:
        name: cloud-creds
      region: {{ .Values.region }}
  provisioning:
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-private-ssh-key
    imageSetRef:
      name: img{{ .Values.version }}-x86-64-appsub
  pullSecretRef:
    name: pull-secret
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.clusterName }}-worker
  namespace: {{ .Values.clusterName }}
spec:
  {{- if eq .Values.autoscaling true }}
  autoscaling:
    maxReplicas: {{ .Values.autoscalingTarget }}
    minReplicas: 3
  {{- end }}
  {{- if eq .Values.autoscaling false }}
  replicas: {{ .Values.workerReplicas }}
  {{- end }}
  clusterDeploymentRef:
    name: {{ .Values.clusterName }}
  name: worker
  platform:
    gcp:
      type: {{ .Values.workerType }}
---
apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
spec: {}


