apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ssh-private-ssh-key
  namespace: {{ .Values.clusterName }}
spec:
  encryptedData:
    ssh-privatekey: AgBl95QcfYAd7vWfGx4ib3G5pQMpJeOS9A+hP/uldU92P+y7lvF8dX1iGNTjXc0yt2OrcvzgLojxuPD47rhIDf7qbZX2+UlTj4mKEsDopbOzVezdU7ghZpn0JFj1FM4dRIbhvXo6sTdcmzyl2qGLvP+45T8SxWydi4ygApGsofF4XvL2xhCy0YnJyDj/87Ob6YHKcynUdhE3xf5dqaYdCr7JwQFkWWfb5kSOKM636OYOn7rWJKPRzrdVG+jtb4M9F89HlNcIr+RD+GrrnpU03weam+eDz+mtNC4bNcvsDBNikNJA03XvZNWu7tmUn1UTTgoS0V0i9OTp83PDpawbF5SDsC9I4aNJQtis0W0aWx0uXVBvc9TimE91eCbX6j3BPXHJbxVrwuGg1Qra1D06ztwhM6PrThOf2fGG1HL3dYhe+IsMSOKcGzu8yQT+bl2G+TeIwbNMAJsmD88xEBRVeqLneKvUM6vvvRba/Ovo9Cck5V9kvR8YmMYxnWUpXmff7tvgiDA5ad7bMPCWxMW/aEyErG+9xr5VRGym4LCWIhKhoIDKQtMPhhuaJH6lSqbI2PMYmF9BjH27d3Kbehbk3Cg+1gZuKda2sAmPPP7ChYAhb5MbeQXLUgBALQNvM1sWawTAJhrUKU0L353kToqxQZT9+Zqu/GmXq1XF22rjfrqOghZqsv4Pi5JkJUHwJvuAnZX+It/R3ItM/OoNkc9btirxJ/3qrkKvvpl7/Pz+FrD7BJL76eX7hKyoIpJ9BrNm8NoNLHVEfjHk+ULqlfTBgS4GeBF4lVw5MXv6uWfUN86wjQ/d0ZAyEQR6Y6A56jFSdxgu2lroJHGMv0yK01sgCkuzQMO8OS8BCrJUlh4VcXtd05GKa4NComQFuIALqotHJJmPOjv9cYilZ7wujA60E05CjxJvCtc8m6ilrQvTzGf41+K8RUHB6z9gPUvGyPoEN0gomhlVmSTXqgsYpFKBJ4ioKQJvyBqQDzzPdifyor10wopfXWIl5vsUesPdrb5VWpoE2I2+ZlEyVabIVlUc5C91Y60QMQSUdJRmaOhyPrrq+2082+LFarg4KPEoRronIuiRWksgxWKhxfBJv8KdrqTffF9prURRd65Gn/APESHLtuMK2VoST+3y9mq4eILNRrMkBb3hbfNH0jSIYt/akhAMUFO9pvFVof8qJN5MOqkI6jWuExOps+gFP4x90MnMiAI1xV26PSuwkIkoLp230q+UG0AglOpA7WH5WvyDCWhFMFlii8EPYKTR9VV7n7ctgM7hkcl0vayqYB/SKfnD8HYghIYbmPx47C6YnipoDU4U9HnDvDKZz8P5DVuQAINj/2R0d4k6QvZgAWKvPVwE3C4dIb88ZcaGuPYpwFcCc4kP1LmvLROpSgt6+5bROlUW68kbMxCgS1OLaCcjf3ku6ZrOjekDPSupburHF31T+tUMtRQJ6+SXtXb8Y/n3SgWAsZnFG7WjKePEiU1QXxL9J+KtF6UiOps+Dtu8cZBrkorXkRCzKWS/G8Eqs5I+tNLNPDHt0I80u3NhqTt8FYVWBlBFlunyjL6APPRClj8VPcaf7kivzdBJ89qjUDlYENt+NivYPiuIwkcgUbSQXqxGxJxmS8AgTflPYF7nQMefXn94qFMPxqsDw0vgKhZ1xMvHqSDQEyQV5SeA8j5/ASLu3tVclUIcMja+OS4PCzjfr67DgY5A6oZXjoxpYvmohPANwhjoCOjQH5n8QoCPqdZDL7ZRK47i3wtwMql6iIh3CnDAz3177MNlOCdNO2ZMvMvBRRvTK4mHMV5C+kLMggq2JsFD2gfg/o4wzuxv6k/Nzku8sCJMTjE36qO2RdS6lVpkEqRgsagUZjXpd82M3VPY/4ndxq+nhwShJS7JtCRmMVtSYxzChRpcktHHd0IOr4oEugY/1RQlMaXvetytCBBfvivIMwGImW/zCqdcf7eNMOlPcjQi27Htbu2EOEdxCERVS8nkNRNIYfl0uK5CouoQTvXLjd5PAIPczoYtrqWARhTXXkJL5mZ64oQGouG8Uuq5ArHoDy6oXmXuUXsrC3jrkP0fPHqr2JkYdaZaHvQ/nPVcIbFAPF+/2mjdZC1dtfDJX2VE05NIGKUrzX/HUvYzsGqk/noXiWMmowiSVBTr6S6VJSZ19hVTvuX7IScY3Fwyqp8egMpB0zPT60Vi3aSysdW52hjzcZjPMy0n/SheqeGqRd0OHFk1eB+q3A51S/F8QDM12N+aUSzmzY9fA23hBMCenpm4TkdPnri1sEtLX/VD2JCF91llnfcCHaVYhp5v3pcYjxkLP5XN8XgPY2SJq/pILML48Cc/ogGSoodTb27XMpKhVtvGZ/9tFPw7rr/s6e6/F5FLpJxycl9GDs3cTCgOmyuMCoAsslYF1tIwe5317c4DHVKorzimH5/yc6uEHMr3cUflqMcO/DDApXcu87y84/JA2n7ejB5PMcwSMcs2sHTfzWiQDWVTXEE5E2V8CkX4sTTAJlwjRALFiY2ANIAZQmMBS8VDokzYjb+IrjHZDbrlcGCRPGhCdI6Lp7AmyuEqwb2rZf8c7LsZllvJof8Co6b6DEMa8arndUurjYmfLaYkhU3JIRSn+OBRepCXqUMqMN7LRWPMXTEcjV8yQBQzmzoDkHZfMgeL7sHLXwn6YQDlDUxpy2cGixrQd5DiLYiM8TqWSI7K9o/B2O4xTViVzzfPjBGN4UsJp2Jto5bjW7irbPWIupl1mpxTax2SZsU+BaaCc9bLG8ZGGWOlkKDTz3tD1Ec5oapR++dqjFLzJ8NElsvvX3S6L1weqgGV7TeqeIKpm0h5F+MhbWgMg3I4+0Wo/UGLDLn1S5eb8nNmKfbtEBDq0vzPHBcNT7Yhc2AtcLfU/I7DZZSuzK5ieJMT1dveunJ1OWXb327/8wcIG8+cD3IAvI+4UoMAbHLn+u8Vm5qwtnKJtCaSgrDXI96BCwD9xTB4ZoyvooLPkAV/76M7fEoadsSUgN2B4FxJj/6B9gpzBMj9gM32M+zVg/dtGciBYCSX+lzEb+i2YNHG0fUU+Rv+LKg0Ktj0g7OmGDRxPRSpvB/OSEgESDwvg+kK5JkHIQ5lXzjjd4tkAzAHxWFhvuDiBpyRaOHD/R9bJT+yiLBZ1pZ1JATHRM0bC5hEGDhTUJ+nAJ2mmgxTANwcJjEixZ9+QFOfhrwmqoTMtyalXzAEJ7rrgxJF6AZ/NAh9m/7lVFRZy5Q76qXnrFH/8YTYfyxIoeSQaoZUP6g3uQb7rwnRAE81jwL7lTOyA/NTXcFbkdzmsEH56JgL/a/tMLAoGna7xgh3bpzoM1hmFkN0+3bsqpMtLbYXZBixSY9BON4n+ME83OHfkKzSFEEAztpHe29NxVQsaNHazXfxRoS3su160t9NY8DinkJ+JLzwcy/EqxNfsq/tGLBQRvS9Jli34/pUM+7Q/eXRRb8pG9aITGbCqkor3NxPx69WJDlk+L1KnTr2Kxyk62cfYnKhWxiH8u2ZAa0Hkw6obJHD6sHeJaU6ZgZ/rLVR9jw218TDl3aUE3MpgWRdGUDkc/URWQMsmmQnvlZiXNYLM/DnsJIRee/NX3Ap/aXc8wEIwr5q1uB/IqiJpM3iyIIIIou4UqQlpGBcWsSroXBbe1SjeDLLagYhXCKhIFWxG8ddU5kPoAw0QV4v9JZ7BgsaeEOWYCxvqv5syoBVObvatDAw4HqXYTB4dEROn4HIGbWC6BNUsIFHJyVPSkEAs9Pa1mTJTH3F20VxGtuI9d11Mh2CdIsdrgwK18zADmd90uqm1LXtiS6MvDP+HXquwoAS/3yNA7AvIKOx/dCF9xe+rBeaLlkJqW0wXJ85wsSfHMQ4faedU7U2rvwlDhhtYzzq292kn7mz6o74RL5RFZ1jOoxhu2brBY0iBzubI6Igte+VI6bdislnshnZJ5pkXJPoYcawOq773XXjYVlPoNct95Mj+7IbbtrEJZP5zGOPT+Anp8ZfJmj9It923P1eBoiB08tW71f5KNv8Tva9XjG2iOwIjIRcUWC6oo4PzRxliQgb5+5XLEzJkBn0cLk8GXCjeqzWyyN7m2vh+3JAAtKhyrZjxgpXNi96QCdtBH+dsSNaIIKUAyXQY2VsMe4pb8xou6zRvyQKaxY/m2yyweUYvEM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ssh-private-ssh-key
      namespace: {{ .Values.clusterName }}
    type: Opaque

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pull-secret
  namespace: {{ .Values.clusterName }}
spec:
  encryptedData:
    .dockerconfigjson: AgAVLQWv8T+NiGNvjqyvizT9Y4iAse3vryYiJN08R9795iPkaC95JVl5e9GupnMonK1z0vuCYPlm1rYyXOsQq/mFHBE4NTQHgYfpIijRsvcG31RLzhtA0B/W6aowpFY4fN92Wl0ds+wz4YIOIZt4rAYaxGSMLiBNzADEMGwSnYNREW3b2VOMz8inQGQBZ2bovvtxjOueKy0L2RSFYYThQJ1EIGBO1VzbIXa5Q1YV0AuMPvDkdtaNvPyM9fHcQAKT4cGCNa6rR6O9gE3ru35e5UydhiPY8v/ZXZkH6qATFD/mFA6PE+wDqPTERQw39z3nZgUPXDjcI5koNzC19cbEyD6xe5EydZFxskksebGl0z6xSckD8HoBCjBrsmife2PkvEhKgqs3kJyLL+3tCwOrHftc9S4s8KPtqPCWLPdjm2233Vgwo5iI2OeDnKpXoXOrB9pIUWR9rzzK4ty6GZP6Qp7h4EoPiy8RjdCJBcrgCIRfFcbx7+npzimEnI3iCitEK5fUTDB7+Pug/MWAOXjcB2/PzUgGBTN/+Yec5WjnM5pKqQ5TCr24GFZjtgvIJExfx+Ue2IwC7NssKOGamZ6yiXZVSABpcuoVArasBdBrGGjciHZ3JVf3OxkIpHbQgZ7+7eMOcckDeMnFMXcKksjm1aJTFvXvuJnIjTs6dvXIsYo8/AfoIMnWHYL9UIAjgLtelFPmYXvRb0xKvduDCVI0umWrTBReHaid5zXxzrqTK0JcD2ThtA1oYwT9Qj2k44xdxSHgUtaYikQ2md/+AQVNdKToL4A4Rjr0hfHaL6auQw3CDvbhXjspBD1tBLtRNFUsVox+QHLKqGFdXSDeYdKNYM0pNlh2bt3MpkPtp8lqxxT76U9X5/H/Nu14YD3+JAc5s4ADHLDpf5RJC0EXjJFIHOkrOak3hz3czp3ElTXZK/7T6kQ474PfoailriHz38TmTPTPuTb4KBgo2K0frq8EXG9UAc/84qpNVe60CpEJRpBuuv/RELbOtHKvhRlMwjwt8/yapenEVMhwDXAyvKEsDDb4TlK0MWWxIJQU4IxQNmOZiOoFqaqbyd/oG1QhD8VFqQq/SiQ32GuigQHHajEn0yy0qIG9wfkHJ/v4bdTUtAOLqTf0PJgUA4iUj9OgG0qbi74cr09l1viRhJ3M+Tv+bR+3d8mCg8He589ZbbZ2FUYwDYd0e/HvmY6dSuSRnT5QUwVUmhpzoppoxbVR9cEwVK7VCQvI8rZdWK3gMGh4U9y+0XwjyaEaVTSYlZqUKj912oJBta1q0a11oBrNU4XrD8pzLBNmYCi+YNfLlByUVsg3EMN7nL82VyFsvzkzQmNZmD4B7gsUQu37i3odJJVKrqc9cbbsn/tMQlAzVkR6dsOdSAj/TmRae+81iPicYVuvWaVsEXOa+/j0yq/f2tKWNDGhA4JtaYcwpLA25rEfqCMw8uTuUHm2nPmyJniWVAKpGVf1B1IW0WTmw0CvAbtcQCB/jHUj4ACsUsCmgzS8WrbV0ne9bMKgbOt6DpoH7TOHZGZy1rYGWUCJXS2Gah7JZJaH65yiMnQ8X3HPBOtWw3LhqMrn/h1QIoJM+QMyAQ0uuJk9dYdceRUujfIxZLrWdps+8u2Hc5OgP+k7XDbA2g7xLnh6KRLXZnUs7EYvPL0ZhvLPopNJiDq7UpA3I3uJ0sogvuSvnSOTeAtqA2EVLhsLOz/WooTxi1h/UHzoHTgGQ93bgwhrdtOySAHfSPOVr8VEi91+fHzIa6YVamm4csefqmd0e3nJG8UpYoLtmb1nHLa3QukDkaAeRrmvZzof+QHJ1jh4UKvu9plF76J58XUAlDDhvheQxpDJ279nRk12e1BA+faB51Xxv7X5qnafJkzVmnQWP8gY7CPMJ39JiC7xrdPEc0LA5ajycQP324wUaJG71gc7JZtieUYSdUzXN8KcwK2JS6OYDD4mdSFCNvDLpf3vAMnsy9B/G7x4+KQSZnLSC3/g0yppWSXrAVpfXW/sxdKa1KK0grjG4vdhB0d4bQpdoRkkJZEpGocUEeiaJv9fFxgcbRtXh4gScx8m2xpkwSVIRaFW6n3CAEwUJTHUHIoYTX/xY0aQBoHdREYsXK5bb8dMRqx7D4d+loPCj+plNZhJtRM/Zvtve26Or7WBFuoAES9+DBv4nkw5zL22/uYRkPOsOBr1tg0ogukEotlJNuNc8QXg9Ysrb84rxEyMSQsqzBU6aWbkYp8W8RAF7oUrM2fthutvW2lhWr/fRhkcCJIfMngta+1I8VXqZF+HNs2ZkeqDecIopXK+LtpEjHaRs+P2xFlk7r6wEf/15oVTJJjrm6dCESqLRWQoBmCnFQczRcgAhi3oErSPKWSwq7BX751gUIpQ8Tz4UqHoTxThywfOGipNhLxpUfxoHpQcgmY1SSvkk3LF9WHD5fsWCxoVe87TGRRcL/bhM+rWMQozKmhBWFiJcj8ZFzb0RHFWU1PRtAQ8o5rdNza+T0xaD0/5jaqO0PDxO0PTQSLPMIJp4HCyJmuHjfXGZ/ZpHomorbsMsVoTTnyfw4UMKIq9WfJIjPHKV71nFlu6p07O1MGjazAgxjM+l3fbzuh158ynegEDzzksI2Ww+N5l/eGcNfYUnL1caglOOgvVztPvow8UY6BMNU2ctO+jqHMEWXGMWrXg4L4ZBcG+YoZgpaN1rctHhUFoaKt4pI+jiDCI4OfsLNzsbjoUOiBxU79aqubd3OpzMrLL4vdnyqKN9+qYf8wj+GWM1tRTA884JVHlpVU0Uwda8RB0G5JVRFfYvDon1jRHDnWa0Q72L8GqiH7Rd2zqkvKhy3lVj6l4xVVpUQ5LsyeYWAhBIBBvWnv11qzphI3UJ92njg/O7/w0+jTyEda8h2F6BrLd5O5rIQFA47PRK8aqmR2VloqiW3BjPF8MZtv0d26+uUqCr2Npg2+n25fD7TB9ZBkgSH36DE2BdJF8aJK0o2ovWd9Sjym953ANxd+Ck4BcIJfx49RaxDhyu4ILQmu64i09tPMy9q91cornz83jyrCGf+HYGmmif7CEuw4mQvqLqTs+qgcCEYPvf4JnegF29PBu8RZpNYQslY/RiugdGKciQGqcg+Q3ygISPP3rva3N3nnLMrlEgYNDt1890WtJSbqr7X7QTjrWzWeGJ4Bh3tDWdlXLUYwmmlVM9CaRWZjDE8psY9TzVlWQfMhxIkR7OJnCvKpkH+0fKjsqUxelRveuKJo2xu0UzSJnxczWtqzsws5vyjBqgBnWzASIAQ6KuE4WlYT+isprOolvm15D2avRBiSlqM/AvKTktjTzMTwWHUMsmqbYCA8wAsYIG8XKo7uIen/SDIvrIAfa4oOZ62Exp7avaT9+AQ4Ypo9vxG/5EY+f2QzXSA1Anx63CeWci0Si12tmE1VwOlKvdnqX8XeFkArCnj/AbmjsASUdXZGwYMPlLcWy7KuUJ2jkGQqLDrDZOOgE4Av1uTgJt4C+PBgYGdYrBdk69QpiDnBW7RAXl19kcGkp1GymBl41JuRcgXXX5xuRwN4uy2oimLRM5iR+7pvBHK65BM4EjNanqG6mxNeMOL8Q4d4h8Fofw+XrCYpa6uuliJD+Qw1+LqmUI5pYO1BuC3q4TST3JHRNc+gDkAxXa59E/bGhb6yrtKUcWHyY0ihzEHa9gZDOoevNW2VUVAejhK7bQX5eofvYC5IeB6cHq2t4M2ACTk53vn1jgA/ig8HyAe53AQFpLT65mR8y70ZOZYNVLsFkd3MVfenWrcUiMhcx5TMQBT0M+A4NfZa1DKrCMuKXr5MIb3FORMq5iJLXJSZoIGfeibmjQ2hmdWEmtX4wIVIRzZpZhHt9gBotY7Y9EXxYQQ6tcGzc5dS5salA3l4jgV/2iq6FQUjyAP4t8nNiOs1EAJbwny/pELeILau4qi8QZdGLg/ZfcV/WI1Gtx88hAE1rzUOXmxj+9l4TDj/5s8bYq2DADPSYRmV7U4IthzWy2rwAyKk1TC4EJt3q7GCsflJR/gZxI+lAEPkJtZT/elRxT8yt304nrlRkNHKvtTaC1CpNIlhw3s/PlvaOO3kC7tkJHXn0jAGBIfEUxwIeMBIDY3kZulpSCRVi5eFdXhz0EhhsnONR1D6L3Ub07Zhzx8ep91TBkGUFwOTj8SIyFlH7NtjXxtwJ4+12yXFyGUMRsEx0hT9yNtCFn5mnQXfs5QDeMGQP5L6FFFNQBDkRnX+Quqjjpc3YtfYVRlbrMPbPbwcWgveVrXo53OzQ+II+ZV5JkVCupBIK4EZ7vAhpMRACQQyCBNrbZUukLyQZdWGwyiWpBxW06JSORSt9QrULYpexnyGNrpV+cz48IQdRDOTGlenTbVTpNMHygR5b1PuCUVqLO9kxBYzV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pull-secret
      namespace: {{ .Values.clusterName }}
    type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: install-config
  namespace: {{ .Values.clusterName }}
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: {{ .Values.clusterName }}
    baseDomain: {{ .Values.baseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        {{- if eq .Values.provider "Google" }}
        gcp:
          type: {{ .Values.workerType }}
        {{- end }}
        {{- if eq .Values.provider "Amazon" }}
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: {{ .Values.workerType }}
        {{- end }}
    compute:
      - hyperthreading: Enabled
        name: 'worker'
        replicas: {{ .Values.workerReplicas }}
        platform:
          {{- if eq .Values.provider "Google" }}
          gcp:
            type: {{ .Values.workerType }}
          {{- end }}
          {{- if eq .Values.provider "Amazon" }}
          aws:
            rootVolume:
              iops: 4000
              size: 100
              type: io1
            type: {{ .Values.workerType }}
          {{- end }}
    networking:
      networkType: OpenShiftSDN
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
      machineNetwork:
        - cidr: 10.0.0.0/16
      serviceNetwork:
        - 172.30.0.0/16
    platform:
      {{- if eq .Values.provider "Google" }}
      gcp:
        projectID: {{ .Values.project }}
        region: {{ .Values.region }}
      {{- end }}
      {{- if eq .Values.provider "Amazon" }}
        region: {{ .Values.region }}
      {{- end }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: {{ .Values.sshKey }}
