{{- if eq .Values.acs.pipelines true }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acs-pipeline-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-app-cicd-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acs-pipeline-secrets
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: rhacs-operator
---
{{- end }}
