{{- if and (hasKey .Values "allure") (hasKey .Values.allure "enabled") (eq .Values.allure.enabled true) }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-allure
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/eformat/allure.git
    path: chart
    targetRevision: main
    helm:
      releaseName: myallure
      parameters:
      - name: security.user
        value: admin
      - name: security.password
        value: password
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-allure
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/sync: "true"
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:     
    - CreateNamespace=true 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/template/spec/containers/0/image
{{- end }}
