{{- if eq .Values.auth.enabled true }}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: htpasswd
    type: HTPasswd
---
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  htpasswd: YWRtaW46JGFwcjEkcHkyUUN4Si8kSTJBN0MwQllGVkcuTko1VHF0LmtwLwp1c2VyOiRhcHIxJHBlTHZYdVRJJFpldWtQeEFDaTRaOVVCd0VUNGg3eDEK
---
apiVersion: v1
kind: Secret
metadata:
  name: v4-0-config-user-idp-1-file-data
  namespace: openshift-authentication
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
users:
  - admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: group-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: cluster-admins
---
{{- end }}
