{{- if eq .Values.auth.enabled true }}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: htpasswd
    type: HTPasswd
---
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: YWRtaW46JGFwcjEkcHkyUUN4Si8kSTJBN0MwQllGVkcuTko1VHF0LmtwLwp1c2VyOiRhcHIxJHBlTHZYdVRJJFpldWtQeEFDaTRaOVVCd0VUNGg3eDEK
---
{{- end }}
