{{- if and (hasKey .Values "mce") (hasKey .Values.mce "enabled") (eq .Values.mce.enabled true) }}

apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: multiclusterengine
spec: {}

{{- end }}

