{{- if and (hasKey .Values "operatorhubio") (hasKey .Values.operatorhubio "enabled") (eq .Values.operatorhubio.enabled true) }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: openshift-marketplace
  annotations:
    operatorframework.io/managed-by: marketplace-operator
spec:
  sourceType: grpc
  image: quay.io/operator-framework/upstream-community-operators:latest
  displayName: OperatorHub.io
  publisher: OperatorHub.io
  updateStrategy:
    registryPoll:
      interval: 10m
{{- end }}
