apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
           cluster.open-cluster-management.io/placement: managed
        requeueAfterSeconds: 180
  template:
    metadata:
      name: global-{{name}}
    spec:
      project: default
      source:
        path: global
        repoURL: 'https://github.com/apoczekalewicz/openshift-cluster-config.git'
        targetRevision: HEAD
        helm:
          valueFiles:
            - managed.yaml
      destination:
        server: "{{server}}"
